[package]
name = "containers"
version = "0.1.0"
edition = "2021"

[lib]
name = "containers"
path = "src/lib.rs"

[dependencies]
ssz_rs = "0.9"
ssz_rs_derive = "0.9"

[dev-dependencies]
rstest = "0.18"
pretty_assertions = "1.4"
